#!/bin/sh
set -e

dst="/var/www/htdocs/$(basename "$(pwd)" '.git')"
src="$dst/raw"

rm -f "$dst/.files"
rm -rf "$src"
git clone . "$src"

"$HOME/bin/ssg3" "$src" "$dst" 'Roman Zolotarev' 'https://www.romanzolotarev.com' > /dev/null
"$HOME/bin/rssg" "$src/index.md" > "$dst/rss.xml"
"$HOME/bin/rssg" "$src/n/index.md" > "$dst/n/rss.xml"

mkdir -p "$dst/src"
(cd "$dst/src" && stagit "$src")
cp -f "$dst/src/log.html" "$dst/src/index.html"
cp -f "$dst/stagit/"* "$dst/src/"
>&2 echo "[stagit] $(grep -c '"commit' "$dst/src/log.html") commits"

hostname > "$dst/hostname"
