#!/bin/sh

LC_ALL='en_US.UTF-8'
PATH="$HOME/bin:$PATH"
PS1='\w '
VISUAL='vi'
export LC_ALL PATH PS1 VISUAL

# shellcheck disable=SC2086
update_complete_pass() {
  pass_list=$(pass ls)
  set -A complete_pass 		-- init passphrase add import show export ls
  set -A complete_pass_add	-- $pass_list
  set -A complete_pass_edit	-- $pass_list
  set -A complete_pass_export	-- $pass_list
  set -A complete_pass_show	-- $pass_list
}
update_complete_pass
pass_add()	{ pass add	"$1" && update_complete_pass; }
pass_edit()	{ pass edit	"$1"; }
pass_show()	{ pass show	"$1"; }
pass_export()	{ pass export	"$1"; }

t()	{ tmux new -As 0; }

c()	{ stmux 'conf'	'prv/conf'; }
j()	{ stmux 'j'	'prv/j'		'vi my.journal'; }
m()	{ stmux 'mus'	'pub/music'	'cmus'; }
nb()	{ stmux 'nb'	'downloads'	'newsboat'; }
v()	{ stmux 'v'	'prv/openvpn'	'doas openvpn --config default.ovpn'; }

alias bsdj='sssg4 src/bsdj'
alias leto='sssg leto'
alias wwwm='sssg4 prv/m'
alias oams='sssg4 src/oams'
alias high5='sssg4 src/high5'
alias runbsd='sssg4 src/runbsd'
alias www='sssg4 src/www'

s_log()	{ test -n "$1" && { rsync -azcvP "$1:/var/www/logs/*" "$HOME/prv/logs/$(date +%Y-%m-%d)-$1/"; }; }

png()	{ optipng -preserve -strip all -o7 "$1"; }
jpeg()	{ jpegoptim --strip-all --preserve --preserve-perms --verbose -m80 $@; }
j50()	{ jpegoptim --strip-all --preserve --preserve-perms --verbose -m50 $@; }
j20() 	{ jpegoptim --strip-all --preserve --preserve-perms --verbose -m20 $@; }
fit()	{ convert -resize 1200 "$1" "$1"; jpeg "$1"; }
f50()	{ convert -resize 50 "$1" "$1"; jpeg "$1"; }
f120()	{ convert -resize 120 "$1" "$1"; jpeg "$1"; }

pics()	{ mnt sd1i && cd DCIM && rsync -avP --chown="$(whoami)" . "$HOME/downloads/pics" && cd "$HOME/downloads/pics" && umnt sd1i; }
xrm()	{ sxiv -tor "${1:-.}" | while read -r f; do test -f "$f" && /bin/rm -v "$f"; done; }
xmv()	{ test -n "$1" || return; mkdir -p "$1"; sxiv -tor . | while read -r f; do mv -v "$f" "$1/"; done; }
x()	{ sxiv -tor "${1:-.}"; }

aria()	{ mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && aria2c "$1"); }
yt()	{ mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl "$1"); }
yl()	{ mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl -f 'bestvideo[height<=144]+bestaudio/best[height<=144]' "$1"); }

p() 	{ PS1='$ '; clear; }

m_sd()	{ doas "$HOME/bin/mnt_crypto"	'36a604aa7599cf63.a' 'fdfc727794396746.a'; }
u_sd()	{ doas "$HOME/bin/umnt_crypto"	'36a604aa7599cf63.a'; }
a_sd()	{ doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/36a604aa7599cf63.a'; }

m_sd2()	{ doas "$HOME/bin/mnt_crypto"	'cca0df756b5bea87.a' '2ee857f508c168b8.a'; }
u_sd2()	{ doas "$HOME/bin/umnt_crypto"	'cca0df756b5bea87.a'; }
a_sd2()	{ doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/cca0df756b5bea87.a'; }

m_hdd()	{ doas "$HOME/bin/mnt_crypto"	'31b1a7c06ca4e505.i' 'c8c569a177ce539a.a'; }
u_hdd()	{ doas "$HOME/bin/umnt_crypto"	'31b1a7c06ca4e505.i'; }
a_hdd()	{ doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/31b1a7c06ca4e505.i'; }

m_xa()	{ doas mkdir -p "/mnt/xa"; doas simple-mtpfs --device 1 "/mnt/xa" -o uid=1000 -o gid=1000 -o allow_other; }
u_xa()	{ doas umount "/mnt/xa"; }

m_u2()	{ doas "$HOME/bin/mnt_crypto"	'4fc37cf1ebe81213.a' '17b4dfdbd3c22759.a'; }
u_u2()	{ doas "$HOME/bin/umnt_crypto"	'4fc37cf1ebe81213.a'; }
a_u2()	{ doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/4fc37cf1ebe81213.a'; }

m_u1()	{ doas "$HOME/bin/mnt_crypto"	'a38cf81c8435b3cd.i' 'e55a17a697d8240d.a'; }
u_u1()	{ doas "$HOME/bin/umnt_crypto"	'a38cf81c8435b3cd.i'; }
a_u1()	{ doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/a38cf81c8435b3cd.i'; }

# alias cabal='env TMPDIR=/usr/local/cabal/build/ cabal'

alias cp='cp -i'
alias l='ls -aF'
alias ll='ls -lahF'
alias mv='mv -i'
alias rm='rm -i'

g() { test -n "$1" && vi $(ag "$1" | fzf | cut -d: -f1); }

alias ga='git add --all -p'
alias gc='git commit'
alias gd='git diff'
alias gf='git commit --amend --no-edit'
alias gl='git log --oneline -30'
alias gp='git push'
alias gr='git rebase -i HEAD~20'
alias gs='git status -sb'

alias a="vi \$HOME/.profile && . \$HOME/.profile"
