#!/bin/sh

PATH=$HOME/bin\
:$HOME/.gem/ruby/2.5/bin\
:/bin\
:/sbin\
:/usr/X11R6/bin\
:/usr/bin\
:/usr/games\
:/usr/local/bin\
:/usr/local/sbin\
:/usr/sbin\
:.
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
TERM=xterm-256color
GIT_PS1_SHOWDIRTYSTATE=true
# shellcheck disable=SC1091
# shellcheck source="$HOME/.gitprompt"
. "$HOME/bin/gitprompt"
PS1="\\[\\e[38;5;247m\\]\\w\$(__git_ps1) \\[\\e[0m\\]"
export PATH LANG LC_ALL TERM GIT_PS1_SHOWDIRTYSTATE

stty -ixon # rescue <C-s> for vim

quits() { aucat -i "$HOME/src/www/quits.wav"; }
# shellcheck disable=SC2086
start_tmux() {
  cd "$2" || return
  cmd="cd $2 && TERM=xterm-256color $3"
  tmux new-session -As 0 -n "$1" "$cmd" 2>/dev/null||
  tmux select-window -t "$1" 2>/dev/null||
  tmux new-window -n "$1" "$cmd" 2>/dev/null
}
o() { start_tmux o "$HOME/src/openvpn" 'doas openvpn --config default.ovpn'; }
m() { start_tmux m "$HOME/pub/music" 'cmus'; }
j() { start_tmux j "$HOME/src/j" 'vim my.journal'; }
www() { start_tmux www "$HOME/src/www" 'vim index.md'; }

export DOCS='/var/www/htdocs/www.romanzolotarev.com'
s() { cd "$HOME/src/www" && ssg watch --clean|| return; }
d() { rsync -avPc --delete-excluded "$DOCS" "$1:/var/www/htdocs/"; quits; }
# shellcheck disable=SC2029
log() { [ -n "$1" ] && [ -n "$2" ] && ssh "$1" "while :; do printf '%s %s %s %s\\n' \"\$(grep \"$2\" /var/www/logs/access.log|cut -f2,13- -d' '|tr -d ' '|sort|uniq|wc -l|tr -d ' ')\" \"\$(date +%Y-%m-%dT%H:%M:%S)\" \"$1\" \"$2\"; sleep 30; done"; }
logt() { log "$1" "$(date "+%d/%b/%Y").*${2:-GET.*HTTP/1\.1. 200}"; }

png() { optipng -preserve -keep -strip all -o7 "$1"; }
jpeg() { cp "$1" "$1.bak" && jpegoptim --strip-all --preserve --preserve-perms --verbose -m80 "$1"; }
fit() { cp "$1" "$1.original" && convert -resize 1200 "$1.original" "$1"; }
fit50() { cp "$1" "$1.original" && convert -resize 50 "$1.original" "$1"; }
alias feh='feh -.Zd'

rebase() { git rebase -i HEAD~"${1:-2}"; }
alias c='PS1=$\ ;clear'
alias cp='cp -i'
alias l='ls -aF'
alias ll='ls -lahF'
alias mv='mv -i'
alias rm='rm -i'
alias du='du -hd1'
alias b="vim \$HOME/.profile && . \$HOME/.profile"

# shellcheck disable=SC2086
update_complete_pass() {
  pass_list=$(pass ls)
  set -A complete_pass -- init passphrase add import show export ls
  set -A complete_pass_add -- $pass_list
  set -A complete_pass_edit -- $pass_list
  set -A complete_pass_export -- $pass_list
  set -A complete_pass_mv -- $pass_list
  set -A complete_pass_show -- $pass_list
}
update_complete_pass
pass_show() { pass show "$1" && update_complete_pass; }
pass_add() { pass add "$1" && update_complete_pass; }
pass_edit() { pass edit "$1"; }
pass_export() { pass export "$1" && update_complete_pass; }

LOCAL_PKG_PATH="$HOME/pub/OpenBSD/$(uname -r)/packages/$(uname -m)"
pkg_add_from_cache() { doas env PKG_PATH="$LOCAL_PKG_PATH" pkg_add "$@"; }
pkg_add_with_cache() { mkdir -p "$LOCAL_PKG_PATH" && doas env PKG_CACHE="$LOCAL_PKG_PATH" pkg_add "$@"; }

mnt() { [ -n "$1" ] && doas mkdir -p "/mnt/$1" && doas mount "/dev/$1" "/mnt/$1" && cd "/mnt/$1" || return; }
umnt() { [ -n "$1" ] && doas umount "/dev/$1"; }
pics() { [ -n "$1" ] && mnt "$1" && cd DCIM && rsync -avPc --chown=romanzolotarev:romanzolotarev . "$HOME/downloads" && cd "$HOME/downloads" && umnt "$1"; }

aria() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && aria2c "$1"); }
yt() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl "$1"); }
yl() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl -f 'bestvideo[height<=144]+bestaudio/best[height<=144]' "$1"); }
