#!/bin/sh

LC_ALL='en_US.UTF-8'
PATH="$HOME/bin:$PATH"
PS1='\w '
VISUAL='vi'
export LC_ALL PATH PS1 VISUAL

# shellcheck disable=SC2086
update_complete_pass() {
  pass_list=$(pass ls)
  set -A complete_pass -- init passphrase add import show export ls
  set -A complete_pass_add -- $pass_list
  set -A complete_pass_edit -- $pass_list
  set -A complete_pass_export -- $pass_list
  set -A complete_pass_show -- $pass_list
}
update_complete_pass
pass_add() { pass add "$1" && update_complete_pass; }
pass_edit() { pass edit "$1"; }
pass_export() { pass export "$1"; }
pass_show() { pass show "$1"; }


j() { stmux 'j' 'prv/j'       'vi my.journal'; }
m() { stmux 'm' 'pub/music'   'cmus'; }
n() { stmux 'n' 'downloads'   'newsboat'; }
v() { stmux 'v' 'prv/openvpn' 'doas openvpn --config default.ovpn'; }

alias bsdj='sssg bsdj'
alias leto='sssg leto'
alias oams='sssg oams'
alias runbsd='sssg runbsd'
alias www='sssg www'
alias zine='sssg zine'

sync_logs() { [ -n "$1" ] && { rsync -azvPc "$1:/var/www/logs/*" "$HOME/prv/logs/$1/"; }; }

png() { optipng -preserve -strip all -o7 "$1"; }
jpeg() { jpegoptim --strip-all --preserve --preserve-perms --verbose -m80 "$1"; }
jpeg50() { jpegoptim --strip-all --preserve --preserve-perms --verbose -m50 "$1"; }
jpeg20() { jpegoptim --strip-all --preserve --preserve-perms --verbose -m20 "$1"; }
fit() { convert -resize 1200 "$1" "$1"; jpeg "$1"; }
fit50() { convert -resize 50 "$1" "$1"; jpeg "$1"; }
fit120() { convert -resize 120 "$1" "$1"; jpeg "$1"; }

pics() { mnt sd1i && cd DCIM && rsync -avP --chown="$(whoami)" . "$HOME/downloads/pics" && cd "$HOME/downloads/pics" && umnt sd1i; }
xrm() { sxiv -tor "${1:-.}" | xargs -r /bin/rm; }
x() { sxiv -tor "${1:-.}"; }

aria() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && aria2c "$1"); }
yt() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl "$1"); }
yl() { mkdir -p "$HOME/downloads" && (cd "$HOME/downloads" && youtube-dl -f 'bestvideo[height<=144]+bestaudio/best[height<=144]' "$1"); }

p() { PS1='$ '; clear; }

mnt_sd()   { doas "$HOME/bin/mnt_crypto"  '87f25794950c8405.a' '83d9c53850315b14.a'; }
umnt_sd()  { doas "$HOME/bin/umnt_crypto" '87f25794950c8405.a'; }
arc_to_sd()  { doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/87f25794950c8405.a'; }

mnt_sd2()  { doas "$HOME/bin/mnt_crypto"  'cca0df756b5bea87.a' '2ee857f508c168b8.a'; }
umnt_sd2() { doas "$HOME/bin/umnt_crypto" 'cca0df756b5bea87.a'; }
arc_to_sd2() { doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/cca0df756b5bea87.a'; }

mnt_hdd()  { doas "$HOME/bin/mnt_crypto"  '31b1a7c06ca4e505.i' 'c8c569a177ce539a.a'; }
umnt_hdd() { doas "$HOME/bin/umnt_crypto" '31b1a7c06ca4e505.i'; }
arc_to_hdd() { doas "$HOME/bin/arc_with_timestamp" "$1" '/mnt/31b1a7c06ca4e505.i'; }


# alias cabal='env TMPDIR=/usr/local/cabal/build/ cabal'

alias cp='cp -i'
alias l='ls -aF'
alias ll='ls -lahF'
alias mv='mv -i'
alias rm='rm -i'

g() { grep -Irle "$1" . ; }

alias ga='git add --all -p'
alias gc='git commit'
alias gd='git diff'
alias gf='git commit -amf'
alias gl='git log --oneline -30'
alias gp='git push'
alias gr='git rebase -i HEAD~20'
alias gs='git status -sb'

alias a="vi \$HOME/.profile && . \$HOME/.profile"
