#!/bin/sh
#
# https://WWW.romanzolotarev.com/openbsd/status
# Copyright 2017-2018 Roman Zolotarev <hi@romanzolotarev.com>
#

screencast_log=/tmp/screencast.log

to_icon() {
	if echo "$1"|grep -q "$2"; then echo "$3"; else echo "$4"; fi
}

cmus="$(cmus-remote -Q 2>/dev/null)"
vol="$(( $(mixerctl outputs.master|cut -d',' -f2 ) * 100 / 255 ))%"

if [ -n "$cmus" ]; then
	printf '%+20s:%-3s %s%s ' \
	"$(echo "$cmus"|grep 'tag title'|cut -c 11-30)" \
	"$(echo "$cmus"|grep 'position'|cut -c 10-)"\
	"$(to_icon "$cmus" 'set shuffle true' 'L' '.')" \
	"$(to_icon "$cmus" 'set repeat_current true' 'R' '.')"
fi

printf '%s %sC ' \
"$(to_icon "$(xset -q|grep LED)" '00000000' 'A' 'Я')" \
"$(sysctl -n hw.sensors.cpu0|cut -d'.' -f1)"

if [ -f "$screencast_log" ]; then
	fps="$(tr '' '\n'<"$screencast_log"|
	grep 'fps= '|
	tail -n1|
	cut -d'=' -f3|
	cut -d' ' -f2)"
	printf '%+2sfps' "${fps:-0}"
else
	date "+%a %e %b %H:%M"
fi
