#!/bin/sh
#
# https://WWW.romanzolotarev.com/openbsd/status
# Copyright 2017-2018 Roman Zolotarev <hi@romanzolotarev.com>
#

screencast_log=/tmp/screencast.log

ifttt() { echo "$1"|grep -q "$2" && echo "$3" || echo "$4"; }

cmus="$(cmus-remote -Q 2>/dev/null)"
position="$(echo "$cmus"|grep 'position'|cut -c 10-)"
second="$(printf "%s" "$position"|tail -c 1)"
if [ "$second" -gt 5 ]; then tag=artist; else tag=title; fi
label="$(echo "$cmus"|grep "tag $tag"|cut -c 11-30)"

if [ -n "$cmus" ]; then printf '%+20s %-3s%s%s' \
	"$label" \
	"$position" \
	"$(ifttt "$cmus" 'set shuffle true' 'L' '.')" \
	"$(ifttt "$cmus" 'set repeat_current true' 'R' '.')"
fi

printf '%s %sC ' \
	"$(ifttt "$(xset -q|grep LED)" '00000000' 'A' 'Я')" \
	"$(sysctl -n hw.sensors.cpu0|cut -d'.' -f1)"

if [ -f "$screencast_log" ]; then
	fps="$(tr '' '\n'<"$screencast_log"|
		grep 'fps= '|
		tail -n1|
		cut -d'=' -f3|
		cut -d' ' -f2)"
	printf '%+2sfps' "${fps:-0}"
else
	date "+%a %b %d %H:%M"
fi
