#!/bin/sh
setxkbmap -option grp:alt_space_toggle us,ru &
xinput --set-prop 7 'Device Accel Constant Deceleration' 5
xset mouse 3 3
xset -b
xsetroot -solid black
xidle -delay 5 -timeout 600 -program "$HOME/bin/lockscreen" &
xterm -e 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 TERM=xterm-256color tmux new-session -As 0' &
cwm
