#!/bin/sh -e
setxkbmap \
	-option 'grp:alt_space_toggle,grp_led:caps,ctrl:nocaps' \
	-layout 'us,ru' &
unclutter -root -idle 2 -noevents &
xidle &
xinput set-button-map 7 1 2 3 5 4 7 6 &
xinput set-prop 7 'Device Accel Constant Deceleration' 1 &
xinput set-prop 8 'Device Accel Constant Deceleration' 2 &
xset -b &
xset mouse 5 1 &
xsetroot -solid black &

exec cwm
