#!/bin/sh

program="$(dirname "$(readlink -f "$0")")/rss"

total=0; nos=0
no() { total=$((total+1)); echo "no ok $total - $1"; nos=$((nos+1)); }
ok() { total=$((total+1)); echo "ok $total - $1"; }
eq() { if [ "$1" = "$2" ]; then ok "$3"; else no "$3"
	printf '\033[32m%s\n\033[31m%s\n\033[m' "$1" "$2"; fi; }
desc() { printf '#\n\033[1m%s\033[m\n' "$1"; }

##########################################################################


desc 'args'

temp=$(mktemp -d)


model=$(cat << EOF
2018-09-17 2018-09-17.html
2018-08-26 2018-08-26.html
EOF
)

echo "$model" | $program

rm -rf "${temp:?}"


##########################################################################

echo "1..$total"
if [ "$nos" -gt 0 ]; then echo "FAILED $nos/$total"; else echo "PASS"; fi
